from talkdoc_core.pdf_ops import fillPDF
import json

# TODO: Make paths relative

if __name__ == "__main__":
    pdf_path = "./pdfs/test_bg.pdf"
    response = {
        "txtfPersonVorname": "Max",
        "txtfPersonNachname": "Mustermann",
        "datePersonGebDatum": "01.01.1990",
        "txtfPersonGebName": "Mustername",
        "txtfPersonGebOrt": "Berlin",
        "txtfPersonGebLand": "Deutschland",
        "txtfPersonStaatsangehoerigkeit": "DE",
        "chbxPersonMaennlich": "ja",
        "chbxPersonWeiblich": "ja",
        "chbxPersonDivers": "ja",
        "chbxPersonKeine": "ja",
        "txtfPersonStr": "Musterstraße",
        "txtfPersonHausnr": "12a",
        "txtfPersonPlz": "12345",
        "txtfPersonOrt": "Berlin",
        "txtfPersonPostfach": "Postfach 123",
        "txtfPersonTel": "+49 123 456789",
        "chbxWohnsitz": "ja",
        "txtareaPersonWohnhaft": "Wohnhaft bei Max Beispiel, Beispielweg 5, 12345 Beispielstadt",
        "txtfKontoinhaber": "Max Mustermann",
        "txtfIBAN": "DE44123412341234123412",
        "chbxKonto": "ja",
        "rbtnPersonSVRVNr": "ja",
        "txtfPersonSVRVNr": "X12345678901",
        "rbtnPersonBetreuer": "ja",
        "datePersonEinreise": "15.08.2015",
        "rbtnPersonAufenthaltsgenehm": "ja",
        "rbtnPersonVerpflichtungserkl": "ja",
        "chbxPersonFamStandLedig": "ja",
        "chbxPersonFamStandVerheiratet": "ja",
        "chbxPersonFamStandVerwitwet": "ja",
        "chbxPersonFamStandEingetrLeben": "ja",
        "chbxPersonFamStandGetrennt": "ja",
        "chbxPersonFamStandGeschieden": "ja",
        "chbxPersonFamStandAufgehobLeben": "ja",
        "datePersonGetrennt": "01.01.2020",
        "chbxPersonAntragBUEGSofort": "ja",
        "chbxPersonAntragBUEGSpaeter": "ja",
        "datePersonAntragBUEG": "01.08.2024",
        "rtbnPersonErwerbsfaehig": "ja",
        "rbtnPersonSchueler": "ja",
        "rbtnPersonSchulbuecher": "ja",
        "rbtnPersonUnterbringung": "ja",
        "rbtnPersonUnter18": "ja",
        "rbtnPersonElternBG": "ja",
        "rbtnPersonAusbildung": "ja",
        "rbtnPersonBerechtigterAsyl": "ja",
        "datePersonAsylbewerberleistung": "01.01.2025",
        "txtfPersonIdentNr": "12345678901",
        "txtfPersonAuslaenderNr": "9876543210",
        "rbtnPersonLetztenDreiJahreBUEG": "ja",
        "txtfPersonLeistungsart": "Arbeitslosengeld",
        "datePersonZeitraumLeistungVon": "01.01.2023",
        "datePersonZeitraumLeistungBis": "01.01.2024",
        "txtfLeistungstraegerName": "Jobcenter Berlin",
        "txtfLeistungstraegerStr": "Behördenweg",
        "txtfLeistungstraegerHausnr": "1",
        "txtfLeistungstraegerPlz": "10115",
        "txtfLeistungstraegerOrt": "Berlin",
        "rbtnPersonAngestellt": "ja",
        "datePersonBeschaeftigung1Von": "01.01.2018",
        "datePersonBeschaeftigung1Bis": "01.01.2020",
        "datePersonBeschaeftigung2Von": "01.02.2020",
        "datePersonBeschaeftigung2Bis": "01.07.2021",
        "rbtnPersonLohnanspruch": "ja",
        "txtfAGName": "Beispiel AG",
        "txtfAGStr": "Musterweg",
        "txtfAGHausnr": "3",
        "txtfAGPlz": "54321",
        "txtfAGOrt": "Beispielstadt",
        "rbtnPersonSelbstaendig": "ja",
        "rbtnPersonEntgeltersatz": "ja",
        "txtfPersonEntgeltersatz": "Krankengeld",
        "datePersonEntgeltersatzVon": "01.06.2022",
        "datePersonEntgeltersatzBis": "01.12.2022",
        "rbtnPersonWehrdienst": "ja",
        "rbtnPersonPflegeAngehoerige": "ja",
        "txtareaPersonLebensunterhalt": "Unterstützung durch Familie",
        "rbtnPersonAndereLeistungen": "ja",
        "chbxPersonLeistungBafoeg": "ja",
        "chbxPersonLeistungBAB": "ja",
        "chbxPersonLeistungWohngeld": "ja",
        "chbxPersonLeistungALG": "ja",
        "chbxPersonLeistungRente": "ja",
        "chbxPersonLeistungKRG": "ja",
        "chbxPersonLeistungKG": "ja",
        "chbxPersonLeistungKIZ": "ja",
        "chbxPersonLeistungSonstiges": "ja",
        "txtfPersonLeistungenSonstiges": "Sonstige Leistungen",
        "rbtnPersonGesundheitlSchaden": "ja",
        "rbtnPersonAnspruchDritter": "ja",
        "rbtnPersonAlleinerziehend": "ja",
        "rbtnPersonSchwanger": "ja",
        "datePersonEntbindung": "01.10.2025",
        "rbtnPersonKostenErnaehrung": "ja",
        "rbtnPersonBehinderung": "ja",
        "rbtnPersonLeistungenTeilhabe": "ja",
        "rbtnPersonUnabweisbarerBedarf": "ja",
        "rbtnPersonStationaereEinricht": "ja",
        "txtfPersonStationaereEinricht": "Krankenhaus",
        "datePersonStationaereEinrichtVon": "01.02.2024",
        "datePersonStationaereEinrichtBis": "01.03.2024",
        "rbtnPersonKVPV": "ja",
        "txtfKVName": "TK",
        "txtfKVNr": "A123456789",
        "rtbnKVWechsel": "ja",
        "rbtnPersonVersichert": "ja",
        "rbtnPersonWohnsituation": "ja",
        "chbxPersonWohnenEhegatte": "ja",
        "chbxPersonWohnenKind": "ja",
        "chbxPersonWohnenKindU15": "ja",
        "chbxPersonWohnenEltern": "ja",
        "chbxPersonWohnenVerwandte": "ja",
        "chbxPersonWohnenSonstige": "ja",
        "rbtnPersonBedarfUnterkunft": "ja",
        "rbtnPersonWarmwasser": "ja",
        "dateUnterschriftPerson": "13.07.2025",
        "dateUnterschriftBetreuer": "13.07.2025",
    }

    json_path = "./form_templates/Buergergeld_Antrag.json"

    with open(json_path, "r") as file:
        source_json = json.load(file)

    fillPDF(pdf_path, source_json, response)
